# Generated by Django 4.1 on 2024-01-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0002_userprofile_links_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bg_img",
            field=models.ImageField(blank=True, null=True, upload_to="bg-img"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio_title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="header",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile-pic"),
        ),
    ]
