# Generated by Django 4.1 on 2024-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0003_userprofile_bg_img_userprofile_bio_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
