get http://127.0.0.1:8000/accounts
Content-Type: application/json
Authorization:Token 59170d73d040c7e9e8c392fbab75d94773a4db20

###
post http://127.0.0.1:8000/accounts/signup
Content-Type: application/json

{"usernae": "medlldd", "password": "okay","confirm_password":"okay",  "email":"mail@gmail.co"}


###
post http://127.0.0.1:8000/accounts/login
Content-Type: application/json

{"username": "medlldd", "password": "okay","confirm_password":"okay",  "email":"mail@gmail.co"}


