// Signup Endpoint
# This endpoint is responsible for creating accounts.
# It can only accept POST request

# This should be a two step process - email verification, and it will be updated soon.
# After signup, the user's profile is created too.

post https://linkproject.pythonanywhere.com/accounts/signup
Content-Type: application/json

{"username": "meee", "password": "Npoje@cct", "email":"nejwbnmt@gmail.co"}


###
// Login Endpoint
# This endpoint allows users to login into their account.
# It accepts only POST request
# email and password are required fields

# the cookies is saved on the frontend after a successful login automatically

post https://linkproject.pythonanywhere.com/accounts/login
Content-Type: application/json

{"password": "mypasword",  "email":"mayowa@gmail.com"}

### 
//  Read and Update User Profile
# This can take get, put methods
# Anybody can view anybody's profile
# Only a user can update his/her profile - so the token must be provided for a put method
# in the /access - access is the username of this specific user.

# In this case, admin is the current user

put https://linkproject.pythonanywhere.com/accounts/userprofile/admin
Content-Type: application/json

{
    "name": "MayowaYusuf",
    "bio": "Programmer",
    "category": "Baller",
    "sub_category": "mechanic",
    "bio_title": "Me against the world",
    "id": "100",
    "links": {
        "twitter": "@Craennie",
        "instagram": "@MayowaYusuf",
        "linkedin": "MayowaYusuf"
    },
    "header": "Newst guy",
    "profile_pic": <insert image>,
    
}

// To test if user is online
###
get https://linkproject.pythonanywhere.com/accounts
Content-Type: application/json
