// Signup Endpoint
# This endpoint is responsible for creating accounts.
# It can only accept POST request
# All the are required
# A token is returned after a successful account creation

# This should be a two step process - email verification, and it will be updated soon.
# After signup, the user's profile is created too.

post https://linkproject.pythonanywhere.com/accounts/signup
Content-Type: application/json

{"username": "meee", "password": "Npoje@cct","confirm_password":"Npoje@cct",  "email":"nejwbnmt@gmail.co"}


###
// Login Endpoint
# This endpoint allows users to login into their account.
# It accepts only POST request
# email and password are required fields
# A token is returned after a successful login

post https://linkproject.pythonanywhere.com/accounts/login
Content-Type: application/json

{"password": "Npoje@cct",  "email":"nejwbnmt@gmail.co"}

### 
//  Read and Update User Profile
# This can take get, put methods
# Anybody can view anybody's profile
# Only a user can update his/her profile - so the token must be provided for a put method
# in the /access - access is the username of this specific user.



put https://linkproject.pythonanywhere.com/accounts/userprofile/admin
Content-Type: application/json
Authorization:Token eb901c282396976b8ea1e9c751247474b07932ab

{
    "name": "MayowaYusuf",
    "bio": "Programmer",
    "category": "Baller",
    "sub_category": "mechanic",
    "bio_title": "Me against the world",
    "id": "100",
    "links": {
        "twitter": "@Craennie",
        "instagram": "@MayowaYusuf",
        "linkedin": "MayowaYusuf"
    },
    "header": "Newst guy"
}
