# Generated by Django 4.1 on 2024-02-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userprofiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio_title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.JSONField(default=dict)),
                ('header', models.CharField(blank=True, max_length=250, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='', null=True, upload_to=userprofiles.models.upload_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
