# Generated by Django 4.1 on 2024-02-14 20:26

from django.db import migrations, models
import userprofiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_userprofile_date_created_userprofile_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=userprofiles.models.upload_image_path),
        ),
    ]
